# This is a basic workflow to help you get started with Actions

name: Github secerets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print secret
        run: | 
          echo "${{ secrets.MY_TOP_SECRET }}"
          echo "${{ secrets.idont }}"

      # Runs a set of commands using the runners shell
      - name: print secret key as environment variables
        run: |
          echo "VARIABL: $MY_TOP_SECRET"
        env:
          MY_TOP_SECRET: ${{ secrets.VARIABL }}
