# This is a basic workflow to help you get started with Actions

name: Artifacts demo

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_1:
    name: Upload Artifact
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Create local file
        run: | 
          echo "Hello this is content" > myfile.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: myfile.txt
          retension-days: 5
        

  Job_2:
    name: Download Artifact
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v
        with:
          name: my-artifact
      - run: |
          cat myfile.txt
